### ISSUE TITLE
Links against libssl & libcrypto?

### ISSUE THREAD

**Issue by dougbtv** [aledbf/coreos-keepalived#1]
@aledbf -- have you run into this yet? I follow your build instructions (thank you so much for this project!) and when I run keepalived, it complains about the links to libssl.so and libbrypto.so -- and exits 0. 

```
coreos0 core # /opt/keepalived/keepalived -c /opt/keepalived/keepalived.conf --dont-fork
/opt/keepalived/keepalived: /lib64/libssl.so.1.0.0: no version information available (required by /opt/keepalived/keepalived)
/opt/keepalived/keepalived: /lib64/libcrypto.so.1.0.0: no version information available (required by /opt/keepalived/keepalived)
coreos0 core # echo $?
0
```

and similarly running with `systemctl`, I get:

```
coreos0 core # systemctl status keepalived
● keepalived.service - Start keepalived service
   Loaded: loaded (/etc/systemd/system/keepalived.service; static)
   Active: inactive (dead)

Dec 12 19:02:36 coreos0 systemd[1]: Starting Start keepalived service...
Dec 12 19:02:36 coreos0 sh[857]: /opt/keepalived/keepalived: /lib64/libssl.so.1.0.0: no version information available (required by /opt/keepalived/keepalived)
Dec 12 19:02:36 coreos0 sh[857]: /opt/keepalived/keepalived: /lib64/libcrypto.so.1.0.0: no version information available (required by /opt/keepalived/keepalived)
Dec 12 19:02:36 coreos0 Keepalived[857]: Starting Keepalived v1.2.13 (12/12,2014)
Dec 12 19:02:36 coreos0 Keepalived[857]: daemon is already running
Dec 12 19:02:36 coreos0 systemd[1]: Started Start keepalived service.
```

**Comment by dougbtv** [comment]
OK, I think this was a red herring. I am able to see it running now. It's not assigning the VIP for me. 

But, what I did do was change the systemd unit. I set it so it's running in the foreground and then logging to stdout so that I can check out the logs with `journalctl` -- if I can get it working more smoothly, I'll submit a PR for you to check out. 

I'll come back here with more findings.

**Comment by aledbf** [comment]
@dougbtv this is an experiment. Actually I'm running pacemaker in a real server but I want an alternative.
I will generate a static binary to avoid any coreos dependency

**Comment by dougbtv** [comment]
It's a nice experiment! I came upon it looking for an idea for IP fail over
with coreos when running on bare metal / my own infrastructure as opposed
to running coreos on AWS or digitalocean etc, where I'd likely use a
sidekick to call an API to move an IP.

Great idea on the static binary.

I'll let you know how my experiment with your experiment goes; I think
you're on to something.

**Comment by dougbtv** [comment]
Alright -- I have an alternative solution if you're interested. Running it inside docker but controlling the host network from there.

I've taken your core idea, but, now have it running in a docker container on the host with `--net=host --privileged=true` so that the Docker container itself can manage the host networking.

Dockerfile:

```
FROM centos:centos7
MAINTAINER Doug Smith <info@laboratoryb.org>
ENV build_date 2014-12-12
RUN yum install -y keepalived
```

Build it with: `docker build -t dougbtv/keepalived`

Note to set where your keepalived.conf is on the host, I have it @ `/opt/keepalived/keepalived.conf` -- and I used your exact configuration.

Run it like so:

```
docker run \
    -v /opt/keepalived/keepalived.conf:/etc/keepalived/keepalived.conf \
    --name=keepalived \
    --privileged=true \
    --net=host \
    -t dougbtv/keepalived \
    /usr/sbin/keepalived -f /etc/keepalived/keepalived.conf --dont-fork --log-console
```

Or I have it in a fleet unit file, which is handy too, like this:

```
[Unit]
Description=keepalived
# After=kamailio@%i.service
# Requires=kamailio@%i.service

[Service]
TimeoutStartSec=0
ExecStartPre=-/usr/bin/docker kill keepalived
ExecStartPre=-/usr/bin/docker rm keepalived
ExecStartPre=/usr/bin/docker pull dougbtv/keepalived:latest
ExecStartPre=/bin/sh -c "/usr/sbin/sysctl -w net.ipv4.ip_nonlocal_bind=1"
ExecStart=/bin/sh -c "/usr/bin/docker run \
    -v /opt/keepalived/keepalived.conf:/etc/keepalived/keepalived.conf \
    --name=keepalived \
    --privileged=true \
    --net=host \
    -t dougbtv/keepalived \
    /usr/sbin/keepalived -f /etc/keepalived/keepalived.conf --dont-fork --log-console"
ExecStop=/usr/bin/docker stop keepalived

[X-Fleet]
# MachineMetadata=boxrole=kamailio
# MachineOf=kamailio@%i.service
Conflicts=keepalived@*.service
```

Excuse the commented out lines that are specific to my setup. I leave them as a reference as how you might decorate it.

I've tested it as far that I can get it to assign the virtual ip! Which is making me feel confident. But I haven't tested with two boxes failing over, but... At least it let me knew it could control the network so far.

Thank you again for your well put together experiment, it helped lead me to this for sure.

**Comment by aledbf** [comment]
@dougbtv I just pushed the static binary compilation

**Comment by aledbf** [comment]
@dougbtv I don't want to run a docker container for this. It's like a binary solution or nothing :)
Glad that this experiment helped someone else

**Comment by dougbtv** [comment]
Awesome on the static build, I'll give it a whirl. I don't blame you for wanting to run it on the host, it still does make sense. Packing it up into a fleet unit fits the rest of my config management scheme, so, that's how I came upon the solution.

**Comment by agend07** [comment]
hi - have a question - why is it better to run keepalived on coreos host vs in docker container? I understand that both ways work and 'container' version seem to be closer to the idea of running everything in container

**Comment by aledbf** [comment]
@agend07 the "objective" of this is just not use docker so I can measure the difference (if there is any). If you run keepalived using docker you need to change the default network settings (check the service in this thread)

**Comment by aledbf** [comment]
Closing. Here's an alternative [aledbf/kube-keepalived-vip](https://github.com/aledbf/kube-keepalived-vip) (to be used in a kubernetes cluster)

**Comment by dougbtv** [comment]
Thanks again for collaborating Manuel, definitely was inspired by this.
Cool, I'll check out the Kubernetes variety, that's neat.
